export const ADD_POKEMON = 'ADD_POKEMON';
export const REMOVE_POKEMON = 'REMOVE_POKEMON';
export const ADD_FAVORITE_POKEMON = 'ADD_FAVORITE_POKEMON';
export const REMOVE_FAVORITE_POKEMON = 'REMOVE_FAVORITE_POKEMON';